language: c
compiler:
- gcc

# Handle git submodules yourself - from https://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci#24600210
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y texlive texlive-lang-german  texlive-latex-recommended  texlive-latex-extra
script: make
# deployment:
after_success:
- ./fablab-document/deployment/deploy.sh
